---
apiVersion: v1
kind: Namespace
metadata:
  name: hanish
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: hanish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: php-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-app
  namespace: hanish
spec:
  type: NodePort
  selector:
    app: php-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
