---
apiVersion: v1
kind: Namespace
metadata:
  name: hanish

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: hanish
spec:
  replicas: 2                          # 2 containers (pods)
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: php-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: php-app
  namespace: hanish
spec:
  type: ClusterIP                      # Changed to ClusterIP; Ingress handles external traffic
  selector:
    app: php-app
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-app-ingress
  namespace: hanish
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: demo.servermaintenance.in
    http:
      paths:
      - path: /php(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: php-app
            port:
              number: 80
