---
apiVersion: v1
kind: Namespace
metadata:
  name: hanish
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: hanish
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: php:8.2-apache
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
          - |
            curl -o /var/www/html/index.php https://raw.githubusercontent.com/servermaintenance-in/hanish/main/index.php \
            && apache2-foreground
---
apiVersion: v1
kind: Service
metadata:
  name: php-app
  namespace: hanish
spec:
  type: ClusterIP
  selector:
    app: php-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-app-ingress
  namespace: hanish
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: demo.servermaintenance.in
    http:
      paths:
      - path: /php(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: php-app
            port:
              number: 80
